// @vitest-environment node
import { RuleTester } from 'eslint';
import { afterAll, describe, it } from 'vitest';
import plugin, { findViolations } from './vertex-ui-plugin.mjs';

RuleTester.afterAll = afterAll;
RuleTester.describe = describe;
RuleTester.it = it;

const tester = new RuleTester({
  languageOptions: { parserOptions: { ecmaFeatures: { jsx: true } } },
});

const invalid = (className, id) => ({
  code: `const view = <div className=${className} />;`,
  errors: [{ message: new RegExp(`\\(${id}:`) }],
});

tester.run('vertex-ui/no-raw-styling', plugin.rules['no-raw-styling'], {
  valid: [
    {
      code: '<div className="flex gap-section px-page-gutter medium:grid-cols-2 text-secondary bg-surface" />',
    },
    { code: '<p className="type-body-long text-start ms-auto pe-actions border-subtle" />' },
    { code: '<span className="font-mono text-status-danger bg-status-neutral max-w-form" />' },
    { code: `<div className={\`grid \${open ? "gap-actions" : "gap-section"}\`} />` },
  ],
  invalid: [
    invalid('"bg-[#07483D]"', 'arbitrary'),
    invalid('"p-[3px] flex"', 'arbitrary'),
    invalid('"hover:w-[37rem]"', 'arbitrary'),
    invalid('"ml-auto"', 'physical'),
    invalid('"medium:pr-section"', 'physical'),
    invalid('"text-right"', 'physical'),
    invalid('"rounded-tl-surface"', 'physical'),
    invalid('"text-slate-600"', 'palette'),
    invalid('"bg-emerald-500"', 'palette'),
    invalid('"border-t-red-500"', 'palette'),
    invalid('"dark:bg-surface"', 'dark'),
    invalid('"medium:dark:text-primary"', 'dark'),
    invalid('"z-50 fixed"', 'layer'),
    invalid('"vx-numeric type-body"', 'internal'),
    invalid('"flex vx-button"', 'internal'),
    invalid('{cond ? "flex" : "text-white"}', 'palette'),
    invalid('{clsx("flex", on && "ml-auto")}', 'physical'),
  ],
});

describe('conformance patterns', () => {
  it('accepts every semantic utility generated by the Tailwind bridge', async () => {
    const { readFileSync } = await import('node:fs');
    const bridge = readFileSync(new URL('../src/generated/tailwind.css', import.meta.url), 'utf8');
    const utilities = [
      ...bridge.matchAll(
        /--(background-color|text-color|border-color|spacing|container)-([\w-]+):/g,
      ),
    ].map(
      ([, namespace, name]) =>
        ({
          'background-color': 'bg',
          'text-color': 'text',
          'border-color': 'border',
          spacing: 'gap',
          container: 'max-w',
        })[namespace] + `-${name}`,
    );
    for (const utility of utilities)
      if (findViolations(utility).length) throw new Error(`False positive: ${utility}`);
  });
});
