/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as DevUiRouteRouteImport } from './routes/dev/ui/route'
import { Route as AppDepartmentsIndexRouteImport } from './routes/_app/departments/index'
import { Route as AppDepartmentsDepartmentIdRouteImport } from './routes/_app/departments/$departmentId'
import { Route as AppPermissionsIndexRouteImport } from './routes/_app/permissions/index'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles/index'
import { Route as AppRolesRoleIdRouteImport } from './routes/_app/roles/$roleId'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppUsersNewRouteImport } from './routes/_app/users/new'
import { Route as DevUiIndexRouteImport } from './routes/dev/ui/index'
import { Route as DevUiSectionRouteImport } from './routes/dev/ui/$section'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DevUiRouteRoute = DevUiRouteRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDepartmentsIndexRoute = AppDepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDepartmentsDepartmentIdRoute =
  AppDepartmentsDepartmentIdRouteImport.update({
    id: '/departments/$departmentId',
    path: '/departments/$departmentId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppPermissionsIndexRoute = AppPermissionsIndexRouteImport.update({
  id: '/permissions/',
  path: '/permissions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesRoleIdRoute = AppRolesRoleIdRouteImport.update({
  id: '/roles/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const DevUiIndexRoute = DevUiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevUiRouteRoute,
} as any)
const DevUiSectionRoute = DevUiSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DevUiRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/dev/ui': typeof DevUiRouteRouteWithChildren
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/dev/ui/$section': typeof DevUiSectionRoute
  '/departments/': typeof AppDepartmentsIndexRoute
  '/permissions/': typeof AppPermissionsIndexRoute
  '/roles/': typeof AppRolesIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/dev/ui/': typeof DevUiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/roles/$roleId': typeof AppRolesRoleIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/users/new': typeof AppUsersNewRoute
  '/dev/ui/$section': typeof DevUiSectionRoute
  '/departments': typeof AppDepartmentsIndexRoute
  '/permissions': typeof AppPermissionsIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/dev/ui': typeof DevUiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/dev/ui': typeof DevUiRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/departments/$departmentId': typeof AppDepartmentsDepartmentIdRoute
  '/_app/roles/$roleId': typeof AppRolesRoleIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/users/new': typeof AppUsersNewRoute
  '/dev/ui/$section': typeof DevUiSectionRoute
  '/_app/departments/': typeof AppDepartmentsIndexRoute
  '/_app/permissions/': typeof AppPermissionsIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/dev/ui/': typeof DevUiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/ui'
    | '/departments/$departmentId'
    | '/roles/$roleId'
    | '/users/$userId'
    | '/users/new'
    | '/dev/ui/$section'
    | '/departments/'
    | '/permissions/'
    | '/roles/'
    | '/users/'
    | '/dev/ui/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/departments/$departmentId'
    | '/roles/$roleId'
    | '/users/$userId'
    | '/users/new'
    | '/dev/ui/$section'
    | '/departments'
    | '/permissions'
    | '/roles'
    | '/users'
    | '/dev/ui'
  id:
    | '__root__'
    | '/_app'
    | '/dev/ui'
    | '/_app/'
    | '/_app/departments/$departmentId'
    | '/_app/roles/$roleId'
    | '/_app/users/$userId'
    | '/_app/users/new'
    | '/dev/ui/$section'
    | '/_app/departments/'
    | '/_app/permissions/'
    | '/_app/roles/'
    | '/_app/users/'
    | '/dev/ui/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  DevUiRouteRoute: typeof DevUiRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/departments/': {
      id: '/_app/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof AppDepartmentsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/departments/$departmentId': {
      id: '/_app/departments/$departmentId'
      path: '/departments/$departmentId'
      fullPath: '/departments/$departmentId'
      preLoaderRoute: typeof AppDepartmentsDepartmentIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/permissions/': {
      id: '/_app/permissions/'
      path: '/permissions'
      fullPath: '/permissions/'
      preLoaderRoute: typeof AppPermissionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/$roleId': {
      id: '/_app/roles/$roleId'
      path: '/roles/$roleId'
      fullPath: '/roles/$roleId'
      preLoaderRoute: typeof AppRolesRoleIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/users/new': {
      id: '/_app/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/dev/ui/': {
      id: '/dev/ui/'
      path: '/'
      fullPath: '/dev/ui/'
      preLoaderRoute: typeof DevUiIndexRouteImport
      parentRoute: typeof DevUiRouteRoute
    }
    '/dev/ui/$section': {
      id: '/dev/ui/$section'
      path: '/$section'
      fullPath: '/dev/ui/$section'
      preLoaderRoute: typeof DevUiSectionRouteImport
      parentRoute: typeof DevUiRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppDepartmentsDepartmentIdRoute: typeof AppDepartmentsDepartmentIdRoute
  AppRolesRoleIdRoute: typeof AppRolesRoleIdRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppDepartmentsIndexRoute: typeof AppDepartmentsIndexRoute
  AppPermissionsIndexRoute: typeof AppPermissionsIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppDepartmentsDepartmentIdRoute: AppDepartmentsDepartmentIdRoute,
  AppRolesRoleIdRoute: AppRolesRoleIdRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppUsersNewRoute: AppUsersNewRoute,
  AppDepartmentsIndexRoute: AppDepartmentsIndexRoute,
  AppPermissionsIndexRoute: AppPermissionsIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface DevUiRouteRouteChildren {
  DevUiSectionRoute: typeof DevUiSectionRoute
  DevUiIndexRoute: typeof DevUiIndexRoute
}

const DevUiRouteRouteChildren: DevUiRouteRouteChildren = {
  DevUiSectionRoute: DevUiSectionRoute,
  DevUiIndexRoute: DevUiIndexRoute,
}

const DevUiRouteRouteWithChildren = DevUiRouteRoute._addFileChildren(
  DevUiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  DevUiRouteRoute: DevUiRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
