#!/usr/bin/env node
/**
 * Creates the ignored local `.env` from `.env.example` with a freshly generated
 * PostgreSQL password. Idempotent: an existing `.env` is never overwritten unless
 * `--force` is passed explicitly.
 *
 *   pnpm env:setup            # create .env if missing
 *   pnpm env:setup -- --force # replace .env (loses local overrides)
 *
 * Uses only Node built-ins so no dependency is needed for secret generation.
 */
import { randomBytes } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const repositoryRoot = resolve(import.meta.dirname, '..');
const examplePath = resolve(repositoryRoot, '.env.example');
const envPath = resolve(repositoryRoot, '.env');
const force = process.argv.includes('--force');

if (existsSync(envPath) && !force) {
  console.log('.env already exists; leaving it untouched (use --force to regenerate).');
  process.exit(0);
}

// URL-safe so the value can be embedded in DATABASE_URL without percent-encoding.
const password = randomBytes(24).toString('base64url');
const template = readFileSync(examplePath, 'utf8');
const rendered = template.replaceAll('<generated by pnpm env:setup>', password);

if (rendered === template) {
  console.error(
    '.env.example no longer contains the password placeholder; refusing to write .env.',
  );
  process.exit(1);
}

writeFileSync(envPath, rendered, { encoding: 'utf8', flag: force ? 'w' : 'wx' });
console.log(`Wrote ${envPath} with a generated local database password.`);
